evaluate: avoid double-free on error handling of bogus objref maps
commit ab1139f807f0d0519a25704e75c442ccb71f7a60 upstream.

commit 98c51aaac42b ("evaluate: bail out if anonymous concat set defines a non concat expression")
clears set->init to avoid a double-free.

Extend this to also handle object maps.
The included bogon triggers a double-free of set->init expression:

Error: unqualified type invalid specified in map definition. Try "typeof expression" instead of "type datatype".
ct helper set ct  saddr map { 1c3:: : "p", dead::beef : "myftp" }
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This might not crash, depending on libc/malloc, but ASAN reports this:
==17728==ERROR: AddressSanitizer: heap-use-after-free on address 0x50b0000005e8 at ..
READ of size 4 at 0x50b0000005e8 thread T0
    #0 0x7f1be3cb7526 in expr_free src/expression.c:87
    #1 0x7f1be3cbdf29 in map_expr_destroy src/expression.c:1488
    #2 0x7f1be3cb74d5 in expr_destroy src/expression.c:80
    #3 0x7f1be3cb75c6 in expr_free src/expression.c:96
    #4 0x7f1be3d5925e in objref_stmt_destroy src/statement.c:331
    #5 0x7f1be3d5831f in stmt_free src/statement.c:56
    #6 0x7f1be3d583c2 in stmt_list_free src/statement.c:66
    #7 0x7f1be3d42805 in rule_free src/rule.c:495
    #8 0x7f1be3d48329 in cmd_free src/rule.c:1417
    #9 0x7f1be3cd2c7c in __nft_run_cmd_from_filename src/libnftables.c:759
    #10 0x7f1be3cd340c in nft_run_cmd_from_filename src/libnftables.c:847
    #11 0x55dcde0440be in main src/main.c:535

Signed-off-by: Florian Westphal <fw@strlen.de>
Reviewed-by: Pablo Neira Ayuso <pablo@netfilter.org>